# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 10:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazivPredmeta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentIme', models.CharField(max_length=30)),
                ('index', models.CharField(max_length=10)),
                ('grad', models.CharField(max_length=30)),
                ('adresa', models.CharField(max_length=50)),
                ('jmbg', models.CharField(max_length=13)),
                ('pol', models.CharField(max_length=1)),
                ('datumRodjenja', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='ocena',
            name='predmet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Predmet'),
        ),
        migrations.AddField(
            model_name='ocena',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
