# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 10:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentPrezime',
            field=models.CharField(default=datetime.datetime(2016, 6, 5, 10, 28, 12, 552000, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='studentIme',
            field=models.CharField(max_length=15),
        ),
    ]
