# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20160605_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='adresa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='datumRodjenja',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='grad',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='pol',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
