# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20160605_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmet',
            name='sifra',
            field=models.CharField(default='I7-1', max_length=4),
            preserve_default=False,
        ),
    ]
