# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_predmet_sifra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='jmbg',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
